version: '3.3'

name: 'biip-auth-api'

services:
  postgres:
    image: postgis/postgis:14-master
    networks:
      - internal
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
      TZ: 'Etc/GMT'
      PGTZ: 'Etc/GMT'

  redis:
    image: redis:7
    networks:
      - internal
    ports:
      - 6671:6379

networks:
  internal:

volumes:
  data:
